/************************************************/
/*        PRIMITIVE - CauseRICrequest               */
/************************************************/
 
  
typedef enum{
    
    E2AP_RAN_FUNCTION_ID_INVALID = 0,    
    E2AP_ACTION_NOT_SUPPORTED = 1,    
    E2AP_EXCESSIVE_ACTIONS = 2,    
    E2AP_DUPLICATE_ACTION = 3,    
    E2AP_DUPLICATE_EVENT_TRIGGER = 4,    
    E2AP_FUNCTION_RESOURCE_LIMIT = 5,    
    E2AP_REQUEST_ID_UNKNOWN = 6,    
    E2AP_INCONSISTENT_ACTION_SUBSEQUENT_ACTION_SEQUENCE = 7,    
    E2AP_CONTROL_MESSAGE_INVALID = 8,    
    E2AP_RIC_CALL_PROCESS_ID_INVALID = 9,    
    E2AP_CONTROL_TIMER_EXPIRED = 10,    
    E2AP_CONTROL_FAILED_TO_EXECUTE = 11,    
    E2AP_SYSTEM_NOT_READY = 12,    
    E2AP_UNSPECIFIED = 13,    
    E2AP_RIC_SUBSCRIPTION_END_TIME_EXPIRED = 14,    
    E2AP_RIC_SUBSCRIPTION_END_TIME_INVALID = 15,    
    E2AP_DUPLICATE_RIC_REQUEST_ID = 16,    
    E2AP_EVENT_TRIGGER_NOT_SUPPORTED = 17,    
    E2AP_REQUESTED_INFORMATION_UNAVAILABLE = 18,    
    E2AP_INVALID_INFORMATION_REQUEST = 19  

}_e2ap_CauseRICrequest_et;// ENUMERATED - P  ?
