/**************************************************/
/* assign_value function for E2nodeConfigurationUpdateAcknowledge */
/**************************************************/
void assign_hardcode_value_E2nodeConfigurationUpdateAcknowledge(e2ap_E2nodeConfigurationUpdateAcknowledge_t* p_E2nodeConfigurationUpdateAcknowledge)
{
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.TransactionID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentInterfaceType
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceNG.AMFName
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceNG
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID.GNB-ID-Choice.gnb-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID.GNB-ID-Choice
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice.enb-ID-macro
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice.enb-ID-shortmacro
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice.enb-ID-longmacro
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceE1.GNB-CU-UP-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceE1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceF1.GNB-DU-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceF1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceW1.NGENB-DU-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceW1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceS1.MMEname
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceS1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.macro-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.home-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.short-Macro-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.long-Macro-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID.ENGNB-ID.gNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID.ENGNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck.updateOutcome
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck.Cause.CauseRICrequest
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck.Cause.CauseRICservice
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck.Cause.CauseE2node
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck.Cause.CauseTransport
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck.Cause.CauseProtocol
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck.Cause.CauseMisc
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck.Cause.CauseServiceLayer.ServiceLayerCause
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck.Cause.CauseServiceLayer
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck.Cause
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item.E2nodeComponentConfigurationAck
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs.E2nodeComponentConfigAdditionAck-Item
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List.E2nodeComponentConfigAdditionAck-ItemIEs
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigAdditionAck-List
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentInterfaceType
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceNG.AMFName
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceNG
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID.GNB-ID-Choice.gnb-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID.GNB-ID-Choice
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice.enb-ID-macro
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice.enb-ID-shortmacro
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice.enb-ID-longmacro
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceE1.GNB-CU-UP-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceE1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceF1.GNB-DU-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceF1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceW1.NGENB-DU-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceW1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceS1.MMEname
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceS1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.macro-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.home-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.short-Macro-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.long-Macro-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID.ENGNB-ID.gNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID.ENGNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck.updateOutcome
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck.Cause.CauseRICrequest
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck.Cause.CauseRICservice
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck.Cause.CauseE2node
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck.Cause.CauseTransport
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck.Cause.CauseProtocol
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck.Cause.CauseMisc
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck.Cause.CauseServiceLayer.ServiceLayerCause
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck.Cause.CauseServiceLayer
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck.Cause
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item.E2nodeComponentConfigurationAck
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs.E2nodeComponentConfigUpdateAck-Item
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List.E2nodeComponentConfigUpdateAck-ItemIEs
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigUpdateAck-List
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentInterfaceType
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceNG.AMFName
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceNG
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID.GNB-ID-Choice.gnb-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID.GNB-ID-Choice
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalgNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice.enb-ID-macro
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice.enb-ID-shortmacro
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice.enb-ID-longmacro
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID.ENB-ID-Choice
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID.GlobalngeNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn.GlobalNG-RANNode-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceXn
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceE1.GNB-CU-UP-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceE1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceF1.GNB-DU-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceF1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceW1.NGENB-DU-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceW1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceS1.MMEname
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceS1
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.macro-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.home-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.short-Macro-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID.long-Macro-eNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID.ENB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalENB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID.PLMN-Identity
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID.ENGNB-ID.gNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID.ENGNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2.GlobalenGNB-ID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID.E2nodeComponentInterfaceX2
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentID
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck.updateOutcome
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck.Cause.CauseRICrequest
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck.Cause.CauseRICservice
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck.Cause.CauseE2node
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck.Cause.CauseTransport
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck.Cause.CauseProtocol
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck.Cause.CauseMisc
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck.Cause.CauseServiceLayer.ServiceLayerCause
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck.Cause.CauseServiceLayer
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck.Cause
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item.E2nodeComponentConfigurationAck
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs.E2nodeComponentConfigRemovalAck-Item
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List.E2nodeComponentConfigRemovalAck-ItemIEs
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs.E2nodeComponentConfigRemovalAck-List
// E2nodeConfigurationUpdateAcknowledge.E2nodeConfigurationUpdateAcknowledge-IEs
// E2nodeConfigurationUpdateAcknowledge


    return;
}


/**************************************************/
/*      encode_E2nodeConfigurationUpdateAcknowledge                    */
/*                                                */
/**************************************************/
/*
E2nodeConfigurationUpdateAcknowledge
    E2nodeConfigurationUpdateAcknowledge-IEs
        TransactionID
        E2nodeComponentConfigAdditionAck-List
            E2nodeComponentConfigAdditionAck-ItemIEs
                E2nodeComponentConfigAdditionAck-Item
                    E2nodeComponentInterfaceType
                    E2nodeComponentID
                        E2nodeComponentInterfaceNG
                            AMFName
                                PrintableString
                        E2nodeComponentInterfaceXn
                            GlobalNG-RANNode-ID
                                GlobalgNB-ID
                                    PLMN-Identity
                                    GNB-ID-Choice
                                        gnb-ID
                                GlobalngeNB-ID
                                    PLMN-Identity
                                    ENB-ID-Choice
                                        enb-ID-macro
                                        enb-ID-shortmacro
                                        enb-ID-longmacro
                        E2nodeComponentInterfaceE1
                            GNB-CU-UP-ID
                        E2nodeComponentInterfaceF1
                            GNB-DU-ID
                        E2nodeComponentInterfaceW1
                            NGENB-DU-ID
                        E2nodeComponentInterfaceS1
                            MMEname
                                PrintableString
                        E2nodeComponentInterfaceX2
                            GlobalENB-ID
                                PLMN-Identity
                                ENB-ID
                                    macro-eNB-ID
                                    home-eNB-ID
                                    short-Macro-eNB-ID
                                    long-Macro-eNB-ID
                            GlobalenGNB-ID
                                PLMN-Identity
                                ENGNB-ID
                                    gNB-ID
                    E2nodeComponentConfigurationAck
                        updateOutcome
                        Cause
                            CauseRICrequest
                            CauseRICservice
                            CauseE2node
                            CauseTransport
                            CauseProtocol
                            CauseMisc
                            CauseServiceLayer
                                ServiceLayerCause
        E2nodeComponentConfigUpdateAck-List
            E2nodeComponentConfigUpdateAck-ItemIEs
                E2nodeComponentConfigUpdateAck-Item
                    E2nodeComponentInterfaceType
                    E2nodeComponentID
                        E2nodeComponentInterfaceNG
                            AMFName
                                PrintableString
                        E2nodeComponentInterfaceXn
                            GlobalNG-RANNode-ID
                                GlobalgNB-ID
                                    PLMN-Identity
                                    GNB-ID-Choice
                                        gnb-ID
                                GlobalngeNB-ID
                                    PLMN-Identity
                                    ENB-ID-Choice
                                        enb-ID-macro
                                        enb-ID-shortmacro
                                        enb-ID-longmacro
                        E2nodeComponentInterfaceE1
                            GNB-CU-UP-ID
                        E2nodeComponentInterfaceF1
                            GNB-DU-ID
                        E2nodeComponentInterfaceW1
                            NGENB-DU-ID
                        E2nodeComponentInterfaceS1
                            MMEname
                                PrintableString
                        E2nodeComponentInterfaceX2
                            GlobalENB-ID
                                PLMN-Identity
                                ENB-ID
                                    macro-eNB-ID
                                    home-eNB-ID
                                    short-Macro-eNB-ID
                                    long-Macro-eNB-ID
                            GlobalenGNB-ID
                                PLMN-Identity
                                ENGNB-ID
                                    gNB-ID
                    E2nodeComponentConfigurationAck
                        updateOutcome
                        Cause
                            CauseRICrequest
                            CauseRICservice
                            CauseE2node
                            CauseTransport
                            CauseProtocol
                            CauseMisc
                            CauseServiceLayer
                                ServiceLayerCause
        E2nodeComponentConfigRemovalAck-List
            E2nodeComponentConfigRemovalAck-ItemIEs
                E2nodeComponentConfigRemovalAck-Item
                    E2nodeComponentInterfaceType
                    E2nodeComponentID
                        E2nodeComponentInterfaceNG
                            AMFName
                                PrintableString
                        E2nodeComponentInterfaceXn
                            GlobalNG-RANNode-ID
                                GlobalgNB-ID
                                    PLMN-Identity
                                    GNB-ID-Choice
                                        gnb-ID
                                GlobalngeNB-ID
                                    PLMN-Identity
                                    ENB-ID-Choice
                                        enb-ID-macro
                                        enb-ID-shortmacro
                                        enb-ID-longmacro
                        E2nodeComponentInterfaceE1
                            GNB-CU-UP-ID
                        E2nodeComponentInterfaceF1
                            GNB-DU-ID
                        E2nodeComponentInterfaceW1
                            NGENB-DU-ID
                        E2nodeComponentInterfaceS1
                            MMEname
                                PrintableString
                        E2nodeComponentInterfaceX2
                            GlobalENB-ID
                                PLMN-Identity
                                ENB-ID
                                    macro-eNB-ID
                                    home-eNB-ID
                                    short-Macro-eNB-ID
                                    long-Macro-eNB-ID
                            GlobalenGNB-ID
                                PLMN-Identity
                                ENGNB-ID
                                    gNB-ID
                    E2nodeComponentConfigurationAck
                        updateOutcome
                        Cause
                            CauseRICrequest
                            CauseRICservice
                            CauseE2node
                            CauseTransport
                            CauseProtocol
                            CauseMisc
                            CauseServiceLayer
                                ServiceLayerCause

*/
xnap_return_et e2ap_encode_E2nodeConfigurationUpdateAcknowledge(
                e2ap_E2nodeConfigurationUpdateAcknowledge_t* p_E2nodeConfigurationUpdateAcknowledge_src,
                UInt8 *p_asn_msg, 
                UInt16* p_asn_msg_len
){
#if 1 // hardcode
    assign_hardcode_value_E2nodeConfigurationUpdateAcknowledge(p_E2nodeConfigurationUpdateAcknowledge_src);
#endif

    xnap_return_et retVal = XNAP_FAILURE;
    OSCTXT asn1_ctx;
    e2ap_E2AP_PDU e2ap_pdu;
    OSRTDListNode* p_node = GNB_PNULL;
    e2ap_E2nodeConfigurationUpdateAcknowledge* p_E2nodeConfigurationUpdateAcknowledge = GNB_PNULL;
    e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element* p_e2ap_protocolIEs_elem = GNB_PNULL;
    /* Initialize ASN.1 context */
    if(0!=rtInitContext(&asn1_ctx)){
        XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: ASN context initialization failed",__FUNCTION__);
        XNAP_UT_TRACE_ENTER();
        return retVal;
    }do{
        XNAP_MEMSET(&e2ap_pdu,0,sizeof(e2ap_E2AP_PDU));
        /*set PDU type to initing/ SSF/ USSF */
        e2ap_pdu.t = T_e2ap_E2AP_PDU_successfulOutcome;
        XNAP_TRACE(XNAP_INFO,"dungnm23 - %s: PDU type set to successfulOutcome",__FUNCTION__);
        e2ap_pdu.u.successfulOutcome = rtxMemAllocType(&asn1_ctx, e2ap_SuccessfulOutcome);
        if(GNB_PNULL==e2ap_pdu.u.successfulOutcome){
            XNAP_TRACE(XNAP_INFO,"dungnm23 - %s: Memory allocation failed for successfulOutcome",__FUNCTION__);
            break;
        }

        asn1Init_e2ap_SuccessfulOutcome(e2ap_pdu.u.successfulOutcome);
        e2ap_pdu.u.successfulOutcome->procedureCode = ASN1V_e2ap_id_E2nodeConfigurationUpdate;
        e2ap_pdu.u.successfulOutcome->criticality = e2ap_reject;
        e2ap_pdu.u.successfulOutcome->value.t = T_E2AP_PDU_Description_e2ap_E2AP_ELEMENTARY_PROCEDURES_E2nodeConfigurationUpdateAcknowledge;
        p_E2nodeConfigurationUpdateAcknowledge = rtxMemAllocType(&asn1_ctx, e2ap_E2nodeConfigurationUpdateAcknowledge);
        if(GNB_PNULL==p_E2nodeConfigurationUpdateAcknowledge){
            XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Memory allocation failed for E2nodeConfigurationUpdateAcknowledge",__FUNCTION__);
            break;
        }else{
            XNAP_TRACE(XNAP_INFO,"dungnm23 - %s: Memory allocation success for E2nodeConfigurationUpdateAcknowledge",__FUNCTION__);
        }

        asn1Init_e2ap_E2nodeConfigurationUpdateAcknowledge(p_E2nodeConfigurationUpdateAcknowledge);
        e2ap_pdu.u.successfulOutcome->value.u.e2nodeConfigurationUpdate = p_E2nodeConfigurationUpdateAcknowledge;

        /* Fill ProtocolIEs */
#if 1 // thiếu check optional bitmask
        {
            /*IE-1   encode id_TransactionID - presence = mandatory*/
            rtxDListAllocNodeAndData(&asn1_ctx,
                                    e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element,
                                    &p_node,
                                    &p_e2ap_protocolIEs_elem);
            if(GNB_PNULL==p_node){
                /* not enough memory */
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Memory allocation failed for e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element",__FUNCTION__);
                break;
            }

            asn1Init_e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element(p_e2ap_protocolIEs_elem);
            /*fill the type of ProtocolIEs _protocolIEs_element*/
            p_e2ap_protocolIEs_elem->id = ASN1V_e2ap_id_TransactionID;
            p_e2ap_protocolIEs_elem->criticality = e2ap_reject;
            p_e2ap_protocolIEs_elem->value.t = T_E2AP_PDU_Contents_e2ap_E2nodeConfigurationUpdateAcknowledge_IEs_id_TransactionID;
             p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_TransactionID = &p_E2nodeConfigurationUpdateAcknowledge_src->id_TransactionID; //assign primitive

            
            /* Append the node to protocolIEs list */
            rtxDListAppendNode(&p_E2nodeConfigurationUpdateAcknowledge->protocolIEs, p_node);
            rrc_asn1PrtToStr_E2AP_PDU(XNAP_ASN, "E2AP PDU", &e2ap_pdu);
        }
#endif
#if 1 // thiếu check optional bitmask
        {
            /*IE-2   encode id_E2nodeComponentConfigAdditionAck - presence = optional*/
            rtxDListAllocNodeAndData(&asn1_ctx,
                                    e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element,
                                    &p_node,
                                    &p_e2ap_protocolIEs_elem);
            if(GNB_PNULL==p_node){
                /* not enough memory */
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Memory allocation failed for e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element",__FUNCTION__);
                break;
            }

            asn1Init_e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element(p_e2ap_protocolIEs_elem);
            /*fill the type of ProtocolIEs _protocolIEs_element*/
            p_e2ap_protocolIEs_elem->id = ASN1V_e2ap_id_E2nodeComponentConfigAdditionAck;
            p_e2ap_protocolIEs_elem->criticality = e2ap_reject;
            p_e2ap_protocolIEs_elem->value.t = T_E2AP_PDU_Contents_e2ap_E2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigAdditionAck;

 
            #if 1 // ko đẩy vào compose nữa
            p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigAdditionAck 
                                = rtxMemAllocType(&asn1_ctx, e2ap_E2nodeComponentConfigAdditionAck_List);
            if(GNB_PNULL==p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigAdditionAck){
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Memory allocation failed for e2ap_id_E2nodeComponentConfigAdditionAck",__FUNCTION__);
                break;
            }
            asn1Init_e2ap_E2nodeComponentConfigAdditionAck_List(p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigAdditionAck);
            #endif
            //message_name.item_type -> type = E2nodeComponentConfigAdditionAck_List
            if(XNAP_FAILURE == e2ap_compose_E2nodeComponentConfigAdditionAck_List(&asn1_ctx, 
                                p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigAdditionAck,
                                &p_E2nodeConfigurationUpdateAcknowledge_src->id_E2nodeComponentConfigAdditionAck)){
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Encoding failed for field E2nodeComponentConfigAdditionAck_List",__FUNCTION__);
                rtFreeContext(&asn1_ctx);
                //XNAP_UT_TRACE_EXIT();
                //return XNAP_FAILURE;
                break;
            }else{
            XNAP_TRACE(XNAP_INFO,"dungnm23 - %s: Encoding success for field E2nodeComponentConfigAdditionAck_List",__FUNCTION__);
            }
            
            /* Append the node to protocolIEs list */
            rtxDListAppendNode(&p_E2nodeConfigurationUpdateAcknowledge->protocolIEs, p_node);
            rrc_asn1PrtToStr_E2AP_PDU(XNAP_ASN, "E2AP PDU", &e2ap_pdu);
        }
#endif
#if 1 // thiếu check optional bitmask
        {
            /*IE-3   encode id_E2nodeComponentConfigUpdateAck - presence = optional*/
            rtxDListAllocNodeAndData(&asn1_ctx,
                                    e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element,
                                    &p_node,
                                    &p_e2ap_protocolIEs_elem);
            if(GNB_PNULL==p_node){
                /* not enough memory */
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Memory allocation failed for e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element",__FUNCTION__);
                break;
            }

            asn1Init_e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element(p_e2ap_protocolIEs_elem);
            /*fill the type of ProtocolIEs _protocolIEs_element*/
            p_e2ap_protocolIEs_elem->id = ASN1V_e2ap_id_E2nodeComponentConfigUpdateAck;
            p_e2ap_protocolIEs_elem->criticality = e2ap_reject;
            p_e2ap_protocolIEs_elem->value.t = T_E2AP_PDU_Contents_e2ap_E2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigUpdateAck;

 
            #if 1 // ko đẩy vào compose nữa
            p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigUpdateAck 
                                = rtxMemAllocType(&asn1_ctx, e2ap_E2nodeComponentConfigUpdateAck_List);
            if(GNB_PNULL==p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigUpdateAck){
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Memory allocation failed for e2ap_id_E2nodeComponentConfigUpdateAck",__FUNCTION__);
                break;
            }
            asn1Init_e2ap_E2nodeComponentConfigUpdateAck_List(p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigUpdateAck);
            #endif
            //message_name.item_type -> type = E2nodeComponentConfigUpdateAck_List
            if(XNAP_FAILURE == e2ap_compose_E2nodeComponentConfigUpdateAck_List(&asn1_ctx, 
                                p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigUpdateAck,
                                &p_E2nodeConfigurationUpdateAcknowledge_src->id_E2nodeComponentConfigUpdateAck)){
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Encoding failed for field E2nodeComponentConfigUpdateAck_List",__FUNCTION__);
                rtFreeContext(&asn1_ctx);
                //XNAP_UT_TRACE_EXIT();
                //return XNAP_FAILURE;
                break;
            }else{
            XNAP_TRACE(XNAP_INFO,"dungnm23 - %s: Encoding success for field E2nodeComponentConfigUpdateAck_List",__FUNCTION__);
            }
            
            /* Append the node to protocolIEs list */
            rtxDListAppendNode(&p_E2nodeConfigurationUpdateAcknowledge->protocolIEs, p_node);
            rrc_asn1PrtToStr_E2AP_PDU(XNAP_ASN, "E2AP PDU", &e2ap_pdu);
        }
#endif
#if 1 // thiếu check optional bitmask
        {
            /*IE-4   encode id_E2nodeComponentConfigRemovalAck - presence = optional*/
            rtxDListAllocNodeAndData(&asn1_ctx,
                                    e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element,
                                    &p_node,
                                    &p_e2ap_protocolIEs_elem);
            if(GNB_PNULL==p_node){
                /* not enough memory */
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Memory allocation failed for e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element",__FUNCTION__);
                break;
            }

            asn1Init_e2ap_E2nodeConfigurationUpdateAcknowledge_protocolIEs_element(p_e2ap_protocolIEs_elem);
            /*fill the type of ProtocolIEs _protocolIEs_element*/
            p_e2ap_protocolIEs_elem->id = ASN1V_e2ap_id_E2nodeComponentConfigRemovalAck;
            p_e2ap_protocolIEs_elem->criticality = e2ap_reject;
            p_e2ap_protocolIEs_elem->value.t = T_E2AP_PDU_Contents_e2ap_E2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigRemovalAck;

 
            #if 1 // ko đẩy vào compose nữa
            p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigRemovalAck 
                                = rtxMemAllocType(&asn1_ctx, e2ap_E2nodeComponentConfigRemovalAck_List);
            if(GNB_PNULL==p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigRemovalAck){
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Memory allocation failed for e2ap_id_E2nodeComponentConfigRemovalAck",__FUNCTION__);
                break;
            }
            asn1Init_e2ap_E2nodeComponentConfigRemovalAck_List(p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigRemovalAck);
            #endif
            //message_name.item_type -> type = E2nodeComponentConfigRemovalAck_List
            if(XNAP_FAILURE == e2ap_compose_E2nodeComponentConfigRemovalAck_List(&asn1_ctx, 
                                p_e2ap_protocolIEs_elem->value.u._e2apE2nodeConfigurationUpdateAcknowledge_IEs_id_E2nodeComponentConfigRemovalAck,
                                &p_E2nodeConfigurationUpdateAcknowledge_src->id_E2nodeComponentConfigRemovalAck)){
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: Encoding failed for field E2nodeComponentConfigRemovalAck_List",__FUNCTION__);
                rtFreeContext(&asn1_ctx);
                //XNAP_UT_TRACE_EXIT();
                //return XNAP_FAILURE;
                break;
            }else{
            XNAP_TRACE(XNAP_INFO,"dungnm23 - %s: Encoding success for field E2nodeComponentConfigRemovalAck_List",__FUNCTION__);
            }
            
            /* Append the node to protocolIEs list */
            rtxDListAppendNode(&p_E2nodeConfigurationUpdateAcknowledge->protocolIEs, p_node);
            rrc_asn1PrtToStr_E2AP_PDU(XNAP_ASN, "E2AP PDU", &e2ap_pdu);
        }
#endif

        /*ASN encode msg*/
        {
            if(RT_OK != pu_setBuffer(&asn1_ctx, p_asn_msg, XNAP_MAX_ASN1_BUF_LEN, TRUE)){
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: pu_setBuffer failed",__FUNCTION__);
                break;
            }
            if(0!=asn1PE_e2ap_E2AP_PDU(&asn1_ctx, &e2ap_pdu)){
                XNAP_TRACE(XNAP_ERROR,"dungnm23 - %s: ASN encoding failed",__FUNCTION__);
                *p_asn_msg_len = (UInt16)pe_GetMsgLen(&asn1_ctx);
                rrc_asn1PrtToStr_E2AP_PDU(XNAP_ASN, "E2AP_PDU", &e2ap_pdu);
                SInt8 buff[500];
                rtxErrGetTextBuf(&asn1_ctx, buff, 500);
                XNAP_TRACE(XNAP_ERROR, "dungnm23 BUFFER[%s], %x", (SInt8*)buff, buff);
                ASN_ERROR_PRINT(&asn1_ctx);
                break;
            }else{
                XNAP_TRACE(XNAP_INFO,"dungnm23 - %s: ASN encoding success",__FUNCTION__);
                *p_asn_msg_len = (UInt16)pe_GetMsgLen(&asn1_ctx);
                rrc_asn1PrtToStr_E2AP_PDU(XNAP_ASN, "E2AP_PDU", &e2ap_pdu);
                retVal = XNAP_SUCCESS;
            }
        }

    }while(0);
    rtFreeContext(&asn1_ctx);
    XNAP_UT_TRACE_EXIT();
    return retVal;
}